export const GET_USER_INFO = 'GET_USER_INFO';
export const LOGIN_BY_EMAIL = 'LOGIN_BY_EMAIL';
export const GET_BOOKMARK = 'GET_BOOKMARK';
export const ADD_CHILD_CLASS = 'ADD_CHILD_CLASS';
export const GET_LINEAR_BOOKMARK = 'GET_LINEAR_BOOKMARK';
