export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_BOOK_CLASS = 'GET_BOOK_CLASS';
export const GET_BOOK_MARK = 'GET_BOOK_MARK';
export const ADD_BOOKCLASS = 'ADD_BOOKCLASS';
export const DELETE_BOOKCLASS = 'DELETE_BOOKCLASS';
export const MODIFY_CLASS = 'MODIFY_CLASS';
export const DELETE_BOOKMARK = 'DELETE_BOOKMARK';
export const ADD_BOOKMARK = 'ADD_BOOKMARK';
